{% set name = "chartlets" %}
{% set version = "0.0.29" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/chartlets/archive/{{ version }}.tar.gz
  sha256: d3fb3d5c68d3af5fd93ecab5cc5a033ef4bec88a5b0d9c8630cdc0827021f09c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./chartlets.py -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
    - altair
  imports:
    - chartlets
  commands:
    - pip check

about:
  summary: Backend for server-configured charts library `Chartlets` powered by Vega Altair.
  home: https://github.com/bcdev/chartlets
  dev_url: https://github.com/bcdev/chartlets
  license: MIT
  license_file:
    - LICENSE
    - chartlets.py/LICENSE

extra:
  recipe-maintainers:
    - forman
    - b-yogesh
