{% set name = "chartlets" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/chartlets/archive/v{{ version }}.tar.gz
  sha256: 1d2a12cd8d7d56cd58ce436e41639b3a79dae6ae254f619bb954cf80b6847a4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./chartlets.py -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }},<3.14

test:
  requires:
    - python {{ python_min }}
    - pip
    - altair >=5.5.0,<6.0.0
  imports:
    - chartlets
  commands:
    - pip check

about:
  summary: Backend for server-configured charts library `Chartlets` powered by Vega Altair.
  home: https://github.com/bcdev/chartlets
  dev_url: https://github.com/bcdev/chartlets
  license: MIT
  license_file:
    - LICENSE
    - chartlets.py/LICENSE

extra:
  recipe-maintainers:
    - forman
    - b-yogesh
    - konstntokas
    - AliceBalfanz
    - TejasMorbagal
    - pont-us
    - thomasstorm
    - TonioF
    - clarasb
