{% set name = "chartlets" %}
{% set version = "0.1.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/chartlets/archive/v{{ version }}.tar.gz
  sha256: 5f4cc050cb704434dd0c13e3bfeb17e53e6ac5f86529e0a97345563c3062201e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./chartlets.py -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2.0
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
    - altair
  imports:
    - chartlets
  commands:
    - pip check

about:
  summary: Backend for server-configured charts library `Chartlets` powered by Vega Altair.
  home: https://github.com/bcdev/chartlets
  dev_url: https://github.com/bcdev/chartlets
  license: MIT
  license_file:
    - LICENSE
    - chartlets.py/LICENSE

extra:
  recipe-maintainers:
    - forman
    - b-yogesh
    - konstntokas
    - AliceBalfanz
    - TejasMorbagal
    - pont-us
    - thomasstorm
    - TonioF
